import { getD1 } from "../db";
import type { Principal } from "./identity";

export type ScheduleWorkItemKind = "todo" | "milestone" | "reminder" | "execution";
export type ScheduleWorkItemStatus = "open" | "in_progress" | "done" | "failed" | "cancelled";
export type ScheduleWorkItemPriority = "low" | "normal" | "high" | "urgent";

export type ScheduleWorkItem = {
  id: string;
  tenant_id: string;
  owner_email: string;
  title: string;
  description: string | null;
  kind: ScheduleWorkItemKind;
  status: ScheduleWorkItemStatus;
  priority: ScheduleWorkItemPriority;
  due_at: string | null;
  reminder_at: string | null;
  source_type: string | null;
  source_id: string | null;
  parent_id: string | null;
  auto_generated: number;
  notify_enabled: number;
  metadata_json: string;
  created_at: string;
  updated_at: string;
};

export type ScheduleAlert = ScheduleWorkItem & { alert_type: "overdue" | "upcoming" };

let schemaReady: Promise<void> | undefined;

export async function ensureSchedulePlanningSchema() {
  if (!schemaReady) {
    schemaReady = (async () => {
      const db = getD1();
      await db.batch([
        db.prepare(`CREATE TABLE IF NOT EXISTS schedule_work_items (
          id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, owner_email TEXT NOT NULL DEFAULT '',
          title TEXT NOT NULL DEFAULT '', description TEXT, kind TEXT NOT NULL DEFAULT 'todo',
          status TEXT NOT NULL DEFAULT 'open', priority TEXT NOT NULL DEFAULT 'normal',
          due_at TEXT, reminder_at TEXT, source_type TEXT, source_id TEXT, parent_id TEXT,
          auto_generated INTEGER NOT NULL DEFAULT 0, notify_enabled INTEGER NOT NULL DEFAULT 1,
          metadata_json TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL, updated_at TEXT NOT NULL
        )`),
        db.prepare(`CREATE TABLE IF NOT EXISTS schedule_notifications (
          id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, owner_email TEXT NOT NULL,
          work_item_id TEXT NOT NULL, scheduled_at TEXT NOT NULL, delivered_at TEXT,
          created_at TEXT NOT NULL
        )`),
      ]);
      const columns = await db.prepare("PRAGMA table_info(schedule_work_items)").all<{ name: string }>();
      const names = new Set((columns.results || []).map((column) => column.name));
      const additions = [
        ["kind", "ALTER TABLE schedule_work_items ADD COLUMN kind TEXT NOT NULL DEFAULT 'todo'"],
        ["priority", "ALTER TABLE schedule_work_items ADD COLUMN priority TEXT NOT NULL DEFAULT 'normal'"],
      ] as const;
      const missing = additions.filter(([name]) => !names.has(name));
      if (missing.length) await db.batch(missing.map(([, sql]) => db.prepare(sql)));
      await db.batch([
        db.prepare("CREATE INDEX IF NOT EXISTS schedule_work_items_tenant_status_idx ON schedule_work_items(tenant_id, owner_email, status, due_at)"),
        db.prepare("CREATE INDEX IF NOT EXISTS schedule_work_items_source_idx ON schedule_work_items(tenant_id, source_type, source_id)"),
        db.prepare("CREATE INDEX IF NOT EXISTS schedule_notifications_due_idx ON schedule_notifications(tenant_id, owner_email, scheduled_at, delivered_at)"),
      ]);
    })().catch((error) => {
      schemaReady = undefined;
      throw error;
    });
  }
  await schemaReady;
}

function nowIso() {
  return new Date().toISOString();
}

function id(prefix: string) {
  return `${prefix}_${crypto.randomUUID().replaceAll("-", "")}`;
}

function normalizeDate(value?: string | null) {
  if (!value) return null;
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? null : date.toISOString();
}

function defaultReminder(dueAt: string | null, notifyEnabled: boolean) {
  if (!dueAt || !notifyEnabled) return null;
  return new Date(Math.max(Date.now(), Date.parse(dueAt) - 15 * 60 * 1000)).toISOString();
}

export async function createScheduleWorkItem(input: {
  principal: Principal;
  title: string;
  description?: string;
  kind?: ScheduleWorkItemKind;
  status?: ScheduleWorkItemStatus;
  priority?: ScheduleWorkItemPriority;
  dueAt?: string | null;
  reminderAt?: string | null;
  sourceType?: string | null;
  sourceId?: string | null;
  parentId?: string | null;
  autoGenerated?: boolean;
  notifyEnabled?: boolean;
  metadata?: Record<string, unknown>;
}) {
  await ensureSchedulePlanningSchema();
  const title = input.title.trim().slice(0, 240);
  if (title.length < 2) throw new Error("업무 제목은 2자 이상이어야 합니다.");
  const db = getD1();
  if (input.sourceType && input.sourceId) {
    const existing = await db.prepare(`SELECT id FROM schedule_work_items
      WHERE tenant_id = ? AND owner_email = ? AND source_type = ? AND source_id = ?
        AND status NOT IN ('done', 'failed', 'cancelled') LIMIT 1`)
      .bind(input.principal.tenantId, input.principal.email, input.sourceType, input.sourceId).first<{ id: string }>();
    if (existing) return existing.id;
  }
  const timestamp = nowIso();
  const dueAt = normalizeDate(input.dueAt);
  const notifyEnabled = input.notifyEnabled !== false;
  const activeStatus = input.status !== "done" && input.status !== "cancelled";
  const reminderAt = normalizeDate(input.reminderAt) || defaultReminder(dueAt, notifyEnabled && activeStatus);
  const workItemId = id("work");
  const metadata = JSON.stringify(input.metadata || {});
  await db.prepare(`INSERT INTO schedule_work_items
    (id, tenant_id, owner_email, title, description, kind, status, priority, due_at, reminder_at,
     source_type, source_id, parent_id, auto_generated, notify_enabled, metadata_json, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`)
    .bind(
      workItemId, input.principal.tenantId, input.principal.email, title,
      input.description?.trim().slice(0, 2000) || null, input.kind || "todo", input.status || "open",
      input.priority || "normal", dueAt, reminderAt, input.sourceType || null, input.sourceId || null,
      input.parentId || null, input.autoGenerated ? 1 : 0, notifyEnabled ? 1 : 0, metadata, timestamp, timestamp,
    ).run();
  if (reminderAt) {
    await db.prepare(`INSERT INTO schedule_notifications
      (id, tenant_id, owner_email, work_item_id, scheduled_at, created_at) VALUES (?, ?, ?, ?, ?, ?)`)
      .bind(id("notification"), input.principal.tenantId, input.principal.email, workItemId, reminderAt, timestamp).run();
  }
  return workItemId;
}

export async function listScheduleWorkItems(principal: Principal, options?: { status?: ScheduleWorkItemStatus | "all"; limit?: number }) {
  await ensureSchedulePlanningSchema();
  const limit = Math.min(Math.max(options?.limit || 100, 1), 200);
  const status = options?.status && options.status !== "all" ? options.status : null;
  const rows = await getD1().prepare(`SELECT * FROM schedule_work_items
    WHERE tenant_id = ? AND owner_email = ? AND (? IS NULL OR status = ?)
    ORDER BY CASE WHEN status IN ('done', 'cancelled') THEN 1 ELSE 0 END, due_at IS NULL, due_at ASC, created_at DESC LIMIT ?`)
    .bind(principal.tenantId, principal.email, status, status, limit).all<ScheduleWorkItem>();
  return rows.results || [];
}

export async function updateScheduleWorkItem(principal: Principal, workItemId: string, patch: {
  title?: string; description?: string; status?: ScheduleWorkItemStatus;
  priority?: ScheduleWorkItemPriority; dueAt?: string | null; notifyEnabled?: boolean;
}) {
  await ensureSchedulePlanningSchema();
  const current = await getD1().prepare("SELECT * FROM schedule_work_items WHERE id = ? AND tenant_id = ? AND owner_email = ?")
    .bind(workItemId, principal.tenantId, principal.email).first<ScheduleWorkItem>();
  if (!current) throw new Error("업무 항목을 찾을 수 없습니다.");
  const title = patch.title === undefined ? current.title : patch.title.trim().slice(0, 240);
  const dueAt = patch.dueAt === undefined ? current.due_at : normalizeDate(patch.dueAt);
  const notifyEnabled = patch.notifyEnabled === undefined ? Boolean(current.notify_enabled) : patch.notifyEnabled;
  const status = patch.status || current.status;
  const reminderAt = defaultReminder(dueAt, notifyEnabled && status !== "done" && status !== "cancelled");
  const updatedAt = nowIso();
  await getD1().prepare(`UPDATE schedule_work_items SET title = ?, description = ?, status = ?, priority = ?,
    due_at = ?, reminder_at = ?, notify_enabled = ?, updated_at = ? WHERE id = ? AND tenant_id = ? AND owner_email = ?`)
    .bind(title, patch.description === undefined ? current.description : patch.description.trim().slice(0, 2000) || null,
      status, patch.priority || current.priority, dueAt, reminderAt, notifyEnabled ? 1 : 0,
      updatedAt, workItemId, principal.tenantId, principal.email).run();
  await getD1().prepare("DELETE FROM schedule_notifications WHERE work_item_id = ? AND delivered_at IS NULL").bind(workItemId).run();
  if (reminderAt) {
    await getD1().prepare(`INSERT INTO schedule_notifications
      (id, tenant_id, owner_email, work_item_id, scheduled_at, created_at) VALUES (?, ?, ?, ?, ?, ?)`)
      .bind(id("notification"), principal.tenantId, principal.email, workItemId, reminderAt, updatedAt).run();
  }
}

export async function deleteScheduleWorkItem(principal: Principal, workItemId: string) {
  await ensureSchedulePlanningSchema();
  await getD1().batch([
    getD1().prepare("DELETE FROM schedule_notifications WHERE work_item_id = ? AND tenant_id = ? AND owner_email = ?").bind(workItemId, principal.tenantId, principal.email),
    getD1().prepare("DELETE FROM schedule_work_items WHERE id = ? AND tenant_id = ? AND owner_email = ?").bind(workItemId, principal.tenantId, principal.email),
  ]);
}

export async function deleteScheduleWorkItemsForSource(principal: Principal, sourceType: string, sourceId: string) {
  await ensureSchedulePlanningSchema();
  await getD1().batch([
    getD1().prepare("DELETE FROM schedule_notifications WHERE tenant_id = ? AND owner_email = ? AND work_item_id IN (SELECT id FROM schedule_work_items WHERE tenant_id = ? AND owner_email = ? AND source_type = ? AND source_id = ?)").bind(principal.tenantId, principal.email, principal.tenantId, principal.email, sourceType, sourceId),
    getD1().prepare("DELETE FROM schedule_work_items WHERE tenant_id = ? AND owner_email = ? AND source_type = ? AND source_id = ?").bind(principal.tenantId, principal.email, sourceType, sourceId),
  ]);
}

export async function deleteScheduleWorkItemsForConversation(principal: Principal, conversationId: string) {
  await ensureSchedulePlanningSchema();
  await getD1().batch([
    getD1().prepare(`DELETE FROM schedule_notifications WHERE tenant_id = ? AND owner_email = ? AND work_item_id IN (
      SELECT id FROM schedule_work_items WHERE tenant_id = ? AND owner_email = ? AND source_type = 'conversation_message'
        AND source_id IN (SELECT id FROM messages WHERE conversation_id = ?))`).bind(principal.tenantId, principal.email, principal.tenantId, principal.email, conversationId),
    getD1().prepare(`DELETE FROM schedule_work_items WHERE tenant_id = ? AND owner_email = ? AND source_type = 'conversation_message'
      AND source_id IN (SELECT id FROM messages WHERE conversation_id = ?)`)
      .bind(principal.tenantId, principal.email, conversationId),
  ]);
}

export async function syncScheduleWorkItemStatus(principal: Principal, sourceType: string, sourceId: string, status: ScheduleWorkItemStatus) {
  await ensureSchedulePlanningSchema();
  const db = getD1();
  const updatedAt = nowIso();
  await db.prepare(`UPDATE schedule_work_items SET status = ?, updated_at = ?
    WHERE tenant_id = ? AND owner_email = ? AND source_type = ? AND source_id = ?`)
    .bind(status, updatedAt, principal.tenantId, principal.email, sourceType, sourceId).run();
  if (status === "done" || status === "cancelled") {
    await db.prepare(`DELETE FROM schedule_notifications WHERE tenant_id = ? AND owner_email = ?
      AND work_item_id IN (SELECT id FROM schedule_work_items WHERE tenant_id = ? AND owner_email = ? AND source_type = ? AND source_id = ?)`)
      .bind(principal.tenantId, principal.email, principal.tenantId, principal.email, sourceType, sourceId).run();
  }
}

export async function listScheduleAlerts(principal: Principal, limit = 8): Promise<ScheduleAlert[]> {
  await ensureSchedulePlanningSchema();
  const now = new Date();
  const horizon = new Date(now.getTime() + 24 * 60 * 60 * 1000).toISOString();
  const rows = await getD1().prepare(`SELECT *, CASE WHEN due_at < ? THEN 'overdue' ELSE 'upcoming' END AS alert_type
    FROM schedule_work_items WHERE tenant_id = ? AND owner_email = ?
      AND status IN ('open', 'in_progress', 'failed') AND due_at IS NOT NULL AND due_at <= ?
    ORDER BY CASE WHEN due_at < ? THEN 0 ELSE 1 END, due_at ASC LIMIT ?`)
    .bind(now.toISOString(), principal.tenantId, principal.email, horizon, now.toISOString(), limit).all<ScheduleAlert>();
  return rows.results || [];
}

export function extractDueAtFromText(text: string, now = new Date()) {
  const kstText = text.toLowerCase();
  const base = new Date(now.toLocaleString("en-US", { timeZone: "Asia/Seoul" }));
  const year = base.getFullYear();
  let month = base.getMonth();
  let day = base.getDate();
  const monthDay = kstText.match(/(\d{1,2})\s*월\s*(\d{1,2})\s*일/);
  if (monthDay) { month = Number(monthDay[1]) - 1; day = Number(monthDay[2]); }
  else if (kstText.includes("모레")) day += 2;
  else if (kstText.includes("내일")) day += 1;
  else if (!kstText.includes("오늘")) return null;
  const time = kstText.match(/(\d{1,2})\s*시(?:\s*(\d{1,2})\s*분)?/);
  const hour = time ? Number(time[1]) + (kstText.includes("오후") && Number(time[1]) < 12 ? 12 : 0) : 18;
  const minute = time?.[2] ? Number(time[2]) : 0;
  const kst = new Date(year, month, day, hour, minute, 0, 0);
  return new Date(kst.getTime() - 9 * 60 * 60 * 1000).toISOString();
}

export async function registerWorkItemFromText(input: { principal: Principal; text: string; sourceId: string }) {
  const text = input.text.trim();
  if (!/(할 일|해야|todo|마감|완료|준비|제출|검토|작성|정리|확인|보고서|회의)/i.test(text)) return null;
  const dueAt = extractDueAtFromText(text);
  return createScheduleWorkItem({
    principal: input.principal,
    title: text.replace(/\s+/g, " ").slice(0, 120),
    description: "대화에서 자동 등록된 업무입니다.",
    kind: "todo",
    priority: /긴급|오늘|마감/.test(text) ? "high" : "normal",
    dueAt,
    sourceType: "conversation_message",
    sourceId: input.sourceId,
    autoGenerated: true,
    notifyEnabled: Boolean(dueAt),
  });
}
